name       : teeworlds
version    : 0.6.4
release    : 4
source     :
    - https://github.com/teeworlds/teeworlds/archive/0.6.4-release.tar.gz : 831afdea9e343cd712382c74b941c6c14adfb9192d32504022b41c2abbb910d7
license    : BSD-3-Clause
component  : games.mmo
summary    : Teeworlds is a free online multiplayer game
description: |
    Battle with up to 16 players in a variety of game modes, including Team Deathmatch and Capture The Flag. You can even design your own maps!
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(python3)
    - pkgconfig(sdl)
    - pkgconfig(x11)
    - bam
    - imagemagick
build      : |
    bam client_release server_release
install    : |
    mkdir -p $installdir/usr/share/teeworlds
    mv data $installdir/usr/share/teeworlds/data
    chmod -R 00644 $installdir/usr/share/teeworlds/data

    install -Dm00755 teeworlds $installdir/usr/bin/teeworlds
    install -Dm00755 teeworlds_srv $installdir/usr/bin/teeworlds_srv

    install -Dm00644 $pkgfiles/teeworlds.desktop $installdir/usr/share/applications/teeworlds.desktop
    convert other/icons/Teeworlds.ico teeworlds.png
    install -Dm00644 teeworlds-0.png $installdir/usr/share/pixmaps/teeworlds.png
