name       : teeworlds
version    : 0.7.0
release    : 6
source     :
    - git|https://github.com/teeworlds/teeworlds.git : 0.7.0
license    : BSD-3-Clause
component  : games.mmo
summary    : Teeworlds is a free online multiplayer game
description: |
    Battle with up to 16 players in a variety of game modes, including Team Deathmatch and Capture The Flag. You can even design your own maps!
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(sdl2)
    - bam
    - imagemagick
build      : |
    bam conf=release
install    : |
    pushd build/x86_64/release
    mkdir -p $installdir/usr/share/teeworlds
    mv data $installdir/usr/share/teeworlds/data
    chmod -R 00644 $installdir/usr/share/teeworlds/data

    install -Dm00755 teeworlds $installdir/usr/bin/teeworlds
    install -Dm00755 teeworlds_srv $installdir/usr/bin/teeworlds_srv
    popd

    install -Dm00644 $pkgfiles/teeworlds.desktop $installdir/usr/share/applications/teeworlds.desktop
    install -dm00644 $installdir/usr/share/pixmaps
    convert other/icons/Teeworlds.ico[0] $installdir/usr/share/pixmaps/teeworlds.png