name       : teeworlds
version    : 0.7.5
release    : 18
source     :
    - https://github.com/teeworlds/teeworlds/releases/download/0.7.5/teeworlds-0.7.5-src.tar.gz : fcde2223398e027434ec96315103e9861fc458161b49b15908dc56b8e7a8ecd9
license    : BSD-3-Clause
component  : games.mmo
summary    : Teeworlds is a free online multiplayer game
description: |
    Battle with up to 16 players in a variety of game modes, including Team Deathmatch and Capture The Flag. You can even design your own maps!
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(sdl2)
    - pkgconfig(wavpack)
    - pkgconfig(x11)
    - imagemagick
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 other/teeworlds.appdata.xml $installdir/usr/share/metainfo/teeworlds.appdata.xml
    install -Dm00644 other/teeworlds.desktop $installdir/usr/share/applications/teeworlds.desktop
    install -dm00644 $installdir/usr/share/pixmaps
    convert other/icons/teeworlds.ico[0] $installdir/usr/share/pixmaps/teeworlds.png
