name       : teeworlds
version    : 0.6.3
release    : 1
source     :
    - https://downloads.teeworlds.com/teeworlds-0.6.3-src.tar.gz : 490ee7c372898761c609af8d7b0c6bd55942c6c6fcd7f361eefa00abfc70077b
license    : BSD-3-Clause
component  : games.mmo
summary    : Teeworlds is a free online multiplayer game
description: |
    Battle with up to 16 players in a variety of game modes, including Team Deathmatch and Capture The Flag. You can even design your own maps!
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(python-3.5)
    - pkgconfig(sdl)
    - pkgconfig(x11)
    - bam
    - imagemagick
setup      : |
    sed -i "s|round(|round_to_int(|g" src/base/math.h
    sed -i "s|round(|round_to_int(|g" src/game/collision.h
    sed -i "s|round(|round_to_int(|g" src/game/editor/layer_tiles.cpp
    sed -i "s|round(|round_to_int(|g" src/game/gamecore.cpp
    sed -i "s|round(|round_to_int(|g" src/game/server/entity.cpp
    sed -i "s|0xFF|-1|g" src/engine/client/client.cpp
build      : |
    bam client_release server_release
install    : |
    mkdir -p $installdir/usr/share/teeworlds
    mv data $installdir/usr/share/teeworlds/data
    chmod -R 00644 $installdir/usr/share/teeworlds/data
  
    install -Dm00755 teeworlds $installdir/usr/bin/teeworlds
    install -Dm00755 teeworlds_srv $installdir/usr/bin/teeworlds_srv
  
    install -Dm00644 $pkgfiles/teeworlds.desktop $installdir/usr/share/applications/teeworlds.desktop
    convert other/icons/Teeworlds.ico teeworlds.png
    install -Dm00644 teeworlds-0.png $installdir/usr/share/pixmaps/teeworlds.png
