name       : teeworlds
version    : 0.7.4
release    : 12
source     :
    - https://github.com/teeworlds/teeworlds/releases/download/0.7.4/teeworlds-0.7.4-src.tar.gz : b18af1d94c53f7ba8d2879d069b1616022a0bf833ac078ffc51c39442061541e
license    : BSD-3-Clause
component  : games.mmo
summary    : Teeworlds is a free online multiplayer game
description: |
    Battle with up to 16 players in a variety of game modes, including Team Deathmatch and Capture The Flag. You can even design your own maps!
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(sdl2)
    - pkgconfig(wavpack)
    - imagemagick
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 other/teeworlds.appdata.xml $installdir/usr/share/metainfo/teeworlds.appdata.xml
    install -Dm00644 other/teeworlds.desktop $installdir/usr/share/applications/teeworlds.desktop
    install -dm00644 $installdir/usr/share/pixmaps
    convert other/icons/teeworlds.ico[0] $installdir/usr/share/pixmaps/teeworlds.png
